# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

%{!?python_sitelib: %define python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}
Name:       mer-kickstarter
Summary:    Create kickstart files for Mer images
Version:    0.14
Release:    1
Group:      System/Base
License:    GPLv2
BuildArch:  noarch
URL:        http://www.merproject.org
Source0:    kickstarter-%{version}.tar.bz2
Source100:  mer-kickstarter.yaml
Requires:   python-yaml
Requires:   python-urlgrabber
Requires:   python-cheetah
Requires:   python-lxml
BuildRequires:  python-devel
BuildRequires:  python-cheetah
BuildRoot:  %{_tmppath}/%{name}-%{version}-build


%description
Create Configuration files to build Mer images



%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
make tmpls
# << build pre

CFLAGS="$RPM_OPT_FLAGS" %{__python} setup.py build

# >> build post
# << build post
%install
rm -rf $RPM_BUILD_ROOT
# >> install pre
# << install pre
%if 0%{?suse_version}
%{__python} setup.py install --root=$RPM_BUILD_ROOT --prefix=%{_prefix}
%else
%{__python} setup.py install --root=$RPM_BUILD_ROOT -O1
%endif

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/*
%{python_sitelib}/*
# << files


